
server:
  port: 8084

spring:
  application:
    name: gateway-service
 
  cloud:
    gateway:
      routes:
      - id: LoansearchModule
        uri: lb://LOAN-SEARCH-SERVICE
        predicates:
        - Path=/loansearch/**
        filters:
        - name: Hystrix
          args:
            name: fallbackCommand
            fallbackUri: forward:/fallback/message