server:
  port: 8084

spring:
  application:
    name: gateway-service
 
  cloud:
    gateway:
      routes:
      - id: LoansearchModule
        uri: http://localhost:8082/
        predicates:
        - Path=/loan/**
        filters:
        - names: Hystrix
          args:
            name: fallbackCommand
            fallbackUri: forward:/fallback/message