server:
  port: 8084
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: loanSearchModule
        uri: lb://LOAN-SEARCH-SERVICE
        predicates:
        - Path=/loan/data/**
        filters:
        - name: Hystrix
          args:
            name: fallbackCommand
            fallbackUri: forward:/fallback/loansearchService
      - id: loginModule
        uri: lb://LOGIN-SERVICE
        predicates:
        - Path=/api/login/**
        filters:
        - name: Hystrix
          args:
            name: fallbackCommand
            fallbackUri: forward:/fallback/loginService